//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPortfolioDetail
    {
        public string PortFolioName { get; set; }
        public string Description { get; set; }
        public string CoverImage { get; set; }
        public string YoutubeVideo { get; set; }
        public string CompanyName { get; set; }
    
        public virtual tblCompanyDetail tblCompanyDetail { get; set; }
    }
}
